version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        DYNAMO_DB_ENDPOINT: ${DYNAMO_DB_ENDPOINT}
        DYNAMO_DB_REGION: ${DYNAMO_DB_REGION}
    restart: always
    ports:
      - 3000:3000
    networks:
      - brain_network
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    ports:
      - 8000:8000
    networks:
      - brain_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  brain_network:
    external: true
